package com.qingshixun.model;

import java.io.Serializable;

public class StudentModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_no
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    private Integer stuNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.studentName
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    private String studentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gender
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.profession
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    private String profession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.direction
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    private String direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.technology
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    private Integer technology;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.ability
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    private Integer ability;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_no
     *
     * @return the value of student.stu_no
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    public Integer getStuNo() {
        return stuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_no
     *
     * @param stuNo the value for student.stu_no
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    public void setStuNo(Integer stuNo) {
        this.stuNo = stuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentName
     *
     * @return the value of student.studentName
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    public String getStudentname() {
        return studentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentName
     *
     * @param studentname the value for student.studentName
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    public void setStudentname(String studentname) {
        this.studentname = studentname == null ? null : studentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gender
     *
     * @return the value of student.gender
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gender
     *
     * @param gender the value for student.gender
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.profession
     *
     * @return the value of student.profession
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.profession
     *
     * @param profession the value for student.profession
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.direction
     *
     * @return the value of student.direction
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.direction
     *
     * @param direction the value for student.direction
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    public void setDirection(String direction) {
        this.direction = direction == null ? null : direction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.technology
     *
     * @return the value of student.technology
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    public Integer getTechnology() {
        return technology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.technology
     *
     * @param technology the value for student.technology
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    public void setTechnology(Integer technology) {
        this.technology = technology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.ability
     *
     * @return the value of student.ability
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    public Integer getAbility() {
        return ability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.ability
     *
     * @param ability the value for student.ability
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    public void setAbility(Integer ability) {
        this.ability = ability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Thu Jan 11 14:00:43 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", stuNo=").append(stuNo);
        sb.append(", studentname=").append(studentname);
        sb.append(", gender=").append(gender);
        sb.append(", profession=").append(profession);
        sb.append(", direction=").append(direction);
        sb.append(", technology=").append(technology);
        sb.append(", ability=").append(ability);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}