package com.qingshixun.dao;

import com.qingshixun.model.StudentModel;
import com.qingshixun.model.StudentModelCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.web.bind.annotation.RequestMapping;

public interface StudentModelMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbggenerated Thu Jan 11 14:00:43 CST 2018
	 */
	int countByExample(StudentModelCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbggenerated Thu Jan 11 14:00:43 CST 2018
	 */
	int deleteByExample(StudentModelCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbggenerated Thu Jan 11 14:00:43 CST 2018
	 */
	int deleteByPrimaryKey(Integer stuNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbggenerated Thu Jan 11 14:00:43 CST 2018
	 */
	int insert(StudentModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbggenerated Thu Jan 11 14:00:43 CST 2018
	 */
	int insertSelective(StudentModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbggenerated Thu Jan 11 14:00:43 CST 2018
	 */
	List<StudentModel> selectByExample(StudentModelCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbggenerated Thu Jan 11 14:00:43 CST 2018
	 */
	StudentModel selectByPrimaryKey(Integer stuNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbggenerated Thu Jan 11 14:00:43 CST 2018
	 */
	int updateByExampleSelective(@Param("record") StudentModel record, @Param("example") StudentModelCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbggenerated Thu Jan 11 14:00:43 CST 2018
	 */
	int updateByExample(@Param("record") StudentModel record, @Param("example") StudentModelCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbggenerated Thu Jan 11 14:00:43 CST 2018
	 */
	int updateByPrimaryKeySelective(StudentModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbggenerated Thu Jan 11 14:00:43 CST 2018
	 */
	int updateByPrimaryKey(StudentModel record);

	// 查询所有学生信息
	List<StudentModel> findAll();

	// 通过性别查询学生信息
	List<StudentModel> findListByGender(String gender);

	// 通过方向查询学生信息
	List<StudentModel> findListByDirection(String direction);

	// 添加一个学生
	void addOne(StudentModel student);
}